表現の修正
takahiroanno2024/election2024 pull request #179
Opened 2024-06-25 16:36 UTC by Tomo-masuda

どのようなルールで都議会に挙げる提案を決めるのかは非常に大事な点です。

2024-06-25 18:05 UTC, yanorei32 requested changes

2024-06-25 18:05 UTC, yanorei32 commented on docs/manifest/democracy.md
> +    - 都民からの賛同を一定数得た提案は、都議会での議題に挙げる
文意が変わっている。
これでは、元の文に存在しなかった意、「賛同の評価が数である」を含んでしまう。
そのため、「数」を消すべきではないだろうか。

```suggestion
    - 都民からの賛同を一定得た提案は、都議会での議題に挙げる
```

2024-06-25 18:07 UTC, yanorei32 commented
Issueタイトルも、「表現の修正」ではなく、「『もの』を『提案』に具体化」などが適切かと思います。

2024-06-25 18:09 UTC, Tomo-masuda commented on docs/manifest/democracy.md
> +    - 都民からの賛同を一定数得た提案は、都議会での議題に挙げる
ChatGPTに聞けば分かると思います。

「都民からの賛同を一定得た提案は..」という日本語は正しくありません。具体的には、「一定得た」という表現が不自然で、日本語の文法や自然な表現として適切ではありません。

正しい表現にするためには、「一定」という言葉と「得た」という動詞の関係を整理する必要があります。以下に適切な表現を示します。

修正案
「都民からの賛同を一定数得た提案は..」

「一定数の賛同」を得るという意味を明確にしています。
「都民から一定の賛同を得た提案は..」

「一定の賛同」という基準に達したことを示します。
「一定の都民から賛同を得た提案は..」

「一定の都民」からの賛同を得たことを強調しています。
「一定数の都民から賛同を得た提案は..」

賛同を得た都民の人数が一定数に達していることを表します。
これらの修正案を文脈に応じて使うことで、より自然で明確な表現になります。

2024-06-25 18:20 UTC, yanorei32 commented on docs/manifest/democracy.md
> +    - 都民からの賛同を一定数得た提案は、都議会での議題に挙げる
「数」が歪みやすい方針で意見公募を行っている為、純粋な「数」で賛同を評価するとは到底思えません。
そのため、「数」という表現が含まれてしまう事、それ自体が問題であると考えます。

以上の理由より、「都民から一定の賛同を得た提案は」は良い表現であると感じます。

一方で、「一定の都民から賛同を得た提案は」では、「一定」が「都民」に対してかかってしまっており、「一部の選別された都民からの賛同が得られた場合に」、という意味に捉えうる文であると考えます。
また、「一定数の都民から賛同を得た提案は」は、本の表現と同様に「数」が含まれていて、適当ではないと考えます。

2024-06-25 18:26 UTC, Tomo-masuda commented on docs/manifest/democracy.md
> +    - 都民からの賛同を一定数得た提案は、都議会での議題に挙げる
最初のコメントで「どのようなルールで都議会に挙げる提案を決めるのかは非常に大事な点です。」と指摘しているのは5W1Hがはっきりしないからです。「一定得た」は日本語としても意味不明だしマニフェストしても曖昧すぎる。何の「一定」なのか意味がわからない。「一定数」以外の「一定」って何かありますか？それが知りたい。安野さんは作家なのでおかしい表現は後で修正するとは思っています。

2024-06-26 05:48 UTC, Tomo-masuda commented on docs/manifest/democracy.md
> +    - 都民からの賛同を一定数得た提案は、都議会での議題に挙げる
@ sio-funmatsu それが具体的に指す政策はなんでしょうか？「都民から一定の賛同を得たもの」とは具体的に何がどうなれば都議会に議題としてあげてもらえるのですか？そういうルールが明確であれば良いのです。

2024-07-01 14:18 UTC, takahiroanno commented
都民からの賛同をえられたかどうかの判断は必ずしも数によらないと思ったのでここでは踏み込まない判断をします

2024-07-01 14:18 UTC, closed without merging