Create Others & Energy
takahiroanno2024/election2024 pull request #256
Opened 2024-07-01 12:54 UTC by tokshibata

5本の柱以外の部分に対する政策変更提案を反映するセクションを作成しました。
そのうち、エネルギー政策部分を加筆しています。

**▼元となった声**
ブロードリスニングの結果から、テクノロジーを押し出した今回の政策実現においては、エネルギー政策の言及が不可欠であるというご指摘や具体的ご提案を複数頂きました。

例１：AI活用の環境への影響を危惧する声
環境への影響         エネルギー消費：AIの運用に伴う高いエネルギー消費が環境に与える負荷。         リソースの浪費：大量のデータ処理に伴う資源の無駄遣い。[#TOKYOAI]
https://x.com/298gama/status/1802420896386400324

例２：匿名フォームからの具体的な政策提案
c) スマートエネルギーマネジメント
   - AIを用いた需要予測システムと連携した、クリーンエネルギーの効率的な供給体制の構築
   - 各家庭やオフィスビルのエネルギー使用状況をリアルタイムで把握し、最適な省エネアドバイスを提供

例３：匿名フォームからのご指摘
仮に23区を世界有数のIT産業集積地帯にした場合の電力・防災対策をどのようにお考えですか？首都直下地震、南海トラフ地震、富士山の噴火など近い将来に予測されている災害が多い中で、江戸時代は海だった地域もある23区をそのような集積地帯にすることにはリスクがあるように感じます。

**▼検討内容**
現状の都のエネルギー政策を確認し、目標と大筋の方向性は妥当であると考えます。
一方で今回安野たかひろが提案する政策が実現すれば、より多くの電力が必要となる可能性が高いです。
そのために、更に追加的に都として取り得るエネルギー政策を検討し追加しました。

2024-07-01 14:00 UTC, takahiroanno requested changes
数点質問を追加しました。

- 現状分析は方向性良いと思います
  - 可能であればどれだけのエネルギーを作らなければならないか？が定量的に示せるとなおよいと思いますが、一旦そこなしでもmergeまではしてよいかと思います
- 打ち手も筋は良いと思いつつ、あと一段階だけなぜそこに着目しているのか？　どれだけ効果が出る見込みがあるのかを一行ずつくらい記載があると背景知識がない人でも読んで納得できるものになりそうです

2024-07-02 00:58 UTC, km2355 commented on docs/manifest/others.md
> +    - 特に自動運転を大々的に活用していく場合には、現状の消費電力とはけた違いの電力が必要になる可能性もある
コネクティッド・自動運転社会→消費電力増加のイメージの試算
以下p15
https://www.meti.go.jp/shingikai/sankoshin/green_innovation/industrial_restructuring/pdf/006_03_00.pdf

2024-07-02 11:22 UTC, tokshibata commented on docs/manifest/others.md
> +    - 特に自動運転を大々的に活用していく場合には、現状の消費電力とはけた違いの電力が必要になる可能性もある
追記しました
https://github.com/takahiroanno2024/election2024/pull/256/commits/1b6515dfb7c49d98be12ac9f9032d21f816aebf2

2024-07-02 11:42 UTC, tokshibata commented on docs/manifest/others.md
> +    - 島しょ部における浮体式洋上風力推進のための企業の技術開発支援と実装のための特区化
追記しました
https://github.com/takahiroanno2024/election2024/pull/256/commits/d1465775263b9f48e9a1478b7c97401ba0a5299d

・水深の深い日本の海では着床式は設置できず浮体式によって導入ポテンシャルが格段に上がる
・導入コストこそ高いが発電規模は大きく電力価格は火力発電並みに抑えられる
・海の生態系に与える影響を少し減らせる可能性がある
・技術・人材を要するため産業・雇用創出に繋がる。今後世界にマーケットが広がるポテンシャルがある

2024-07-02 11:53 UTC, tokshibata commented on docs/manifest/others.md
> +        - ディマンドリスポンスの仕組みを拡充。より広い都民にとってメリットを生み、環境インパクトを向上する方法を模索
解説を追記しました。https://github.com/takahiroanno2024/election2024/pull/256/commits/dbdf4f55485e8c32fc159a4d83be0e3aea6fe4e7

定義はエネルギー庁の資料に則っています。
https://www.enecho.meti.go.jp/category/electricity_and_gas/electricity_measures/dr/dr.html

2024-07-02 14:30 UTC, Okayuh commented on docs/manifest/others.md
> +    - 住宅の断熱義務化（ZEH、ZEB推進）
外野からすみません。
https://www.city.kitakyushu.lg.jp/contents/924_01473.html
及びそのリンク先のトークセッションの15分〜20分過ぎあたりを背景情報としてコメントしておきます。

2024-07-02 23:52 UTC, ksuk3ito commented on docs/manifest/others.md
> +    - 島しょ部における浮体式洋上風力推進のための企業の技術開発支援と実装のための特区化
現実的に選択肢となる非化石燃料が､太陽光or風力｡
太陽光1sqm当りの発電容量がだいたい0.1kW. 
太陽光の1日当り発電力 = 約2.7kWh/kW･day
太陽光1sqm当りの発電力 = 0.27kWh/sqm･day
東京都の2022年消費電力=758億kWh --> 1日当り約2076万kWh
[https://www.kankyo.metro.tokyo.lg.jp/climate/renewable_energy/200100a20180214152237412#:~:text=%E9%83%BD%E5%86%85%E3%81%AE2022%E5%B9%B4%E5%BA%A6%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B,22.0%25%20%E3%81%AB%E7%9B%B8%E5%BD%93%E3%81%97%E3%81%BE%E3%81%99%E3%80%82]
発電したものを全て保管しておけ､さらに十分な需要応答力があるすれば(これはかなり強い仮説であり､現実には不可能なので他の発電力が必要となる)､7700haの太陽光パネル面積を用意すれば良い｡
都内には､37000haの宅地が存在しているため､宅地面積の約20%に太陽光パネルをつけきれれば基本的には､太陽光で十分賄えると考えられる｡
[https://www.toshiseibi.metro.tokyo.lg.jp/seisaku/tochi_c/tochi_kekka_r3.html]

一方､全ての太陽光を系統接続し十分な電力を蓄電池等に保管､ピーク時需要への対応なども考えるとそれだけでは不足する可能性がある｡また､このレベルまで太陽光を増やした場合には､保管側での容量が不足し､発電しても電力が買い取られず結果として太陽光パネルの追加や付け替えが機能しなくなる恐れもある｡またミクロでの電力供給に依存する体制となることから供給能力を保証し続けることが困難となる可能性がある｡

これに対して､風力エネルギーを利用する場合の利点は､1風車当りの出力が2MW~と高出力で､発電所数をミニマムに抑えながら再生可能エネルギーを利用出来ることがある｡
ただし､東京近郊の海における気候条件(風が吹き続けるか)や近隣県との関係性､海運･漁業など含めた立地可能性､必要出力の確保などの観点で基幹電力としうるかには疑問の余地があるのに加え技術的にもまだ検証段階にあることを考慮に入れた上で政策的な判断が必要｡

2024-07-03 02:57 UTC, takahiroanno commented on docs/manifest/others.md
> +    - 住宅の断熱義務化（ZEH、ZEB推進）
日本の住宅の断熱効率に向上の余地があり、それが経済性ともに政策として取り組む意義があるというデータが現状まだないので、そこはカットしつつこのPRはマージしちゃいます

```suggestion
```

2024-07-03 02:58 UTC, takahiroanno approved these changes

2024-07-03 02:58 UTC, merged